CREATE TABLE USERS (
  IDENTIFICATION NUMERIC NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  GENDER VARCHAR(20),
  DATE_OF_BIRTH DATE,
  ADDRESS_CITY VARCHAR(50),
    ADDRESS VARCHAR(50),
    POSTAL_CODE VARCHAR(10)

);

CREATE TABLE EMAIL
(
  EMAIL_ID INT NOT NULL PRIMARY KEY,
  IDENTIFICATION INT,
  EMAIL VARCHAR(50),
  EMAIL_TYPE VARCHAR(20)
);


CREATE SEQUENCE Email_Seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 50